### ISSUE TITLE
ImportError: No module named crazyflie

### ISSUE THREAD

**Issue by vinaybysani** [dineshkumar-cse/ElateCopter#1]
Am getting the following error when control_coptor is ran.
Any idea?

Traceback (most recent call last):
  File "control_copter.py", line 5, in <module>
    from copter_interface import CopterInterface
  File "/home/arcl/git/ElateCopter/copter_interface.py", line 5, in <module>
    from crazyflie import Crazyflie
ImportError: No module named crazyflie

**Comment by devdinu** [comment]
Hi @vinaybysani,

you have to download crazyflie repo/lib and add it to your search path.

along with that we need to add the packages manually, say in`$PYTHON_DIR/lib/pythonX.X/site-packages/crazyflie_custom_imports.pth`
```
/usr/local/Cellar/pyqt/4.11.4/lib/python3.4/site-packages
$CRAZYFLIE/CrazyFlie/crazyflie-clients-python/src/cflib
$CRAZYFLIE/CrazyFlie/crazyflie-clients-python/src/cflib/cflib
$CRAZYFLIE/CrazyFlie/crazyflie-clients-python/src
```
lemme know if you face any issues.
